# Generated by Django 2.2.3 on 2019-08-03 15:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=2000)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField(default=0)),
                ('is_offer', models.BooleanField(default=False)),
                ('date_pub', models.DateField(default=datetime.datetime(2019, 8, 3, 15, 4, 40, 668290, tzinfo=utc))),
            ],
            options={
                'ordering': ['date_pub'],
            },
        ),
    ]
