# Generated by Django 2.2.3 on 2019-08-05 18:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='date_pub',
            field=models.DateField(default=datetime.datetime(2019, 8, 5, 18, 22, 40, 449866, tzinfo=utc)),
        ),
    ]
